/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import javax.swing.JOptionPane;
import projetointegrador.dao.AutoresDAO;
import projetointegrador.dao.Conector;
import projetointegrador.telas.CadastroAutor;
import projetointegrador.telas.InfoAutor;
import projetointegrador.telas.TelaPrincipal;
import interfaces.GlobalInterface;

/**
 *
 * @author Gato Sagrado
 */
public class PnAutorGerenciar extends javax.swing.JPanel {
    
    public int id;
    private GlobalInterface listener;

    /**
     * Creates new form PnAutorGerenciar
     */
    public PnAutorGerenciar(int id, String nome, String movimento) {
        initComponents();
        this.id = id;
        LbId.setText(String.valueOf(id));
        LbNome.setText(nome);
        LbMovimento.setText(movimento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAutor = new javax.swing.JButton();
        LbNome = new javax.swing.JLabel();
        LbMovimento = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 50));
        setMinimumSize(new java.awt.Dimension(1180, 50));
        setPreferredSize(new java.awt.Dimension(1180, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtAutor.setBackground(new java.awt.Color(144, 144, 144));
        BtAutor.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtAutor.setForeground(new java.awt.Color(109, 37, 172));
        BtAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMais.png"))); // NOI18N
        BtAutor.setToolTipText("Abre as informações do autor");
        BtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAutorActionPerformed(evt);
            }
        });
        add(BtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 30, 30));

        LbNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbNome.setText("Nome");
        add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, -1, -1));

        LbMovimento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbMovimento.setText("Movimento");
        add(LbMovimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 15, -1, -1));

        LbId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbId.setText("ID");
        add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        BtEditar.setBackground(new java.awt.Color(144, 144, 144));
        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconEdit.png"))); // NOI18N
        BtEditar.setToolTipText("Altera as informações do autor");
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 30, 30));

        BtExcluir.setBackground(new java.awt.Color(144, 144, 144));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLixo.png"))); // NOI18N
        BtExcluir.setToolTipText("Exclui o autor");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAutorActionPerformed
        TelaPrincipal.sobrepor(new InfoAutor(id));
    }//GEN-LAST:event_BtAutorActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        TelaPrincipal.sobrepor(new CadastroAutor(listener, id));
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try{
            String input = JOptionPane.showInputDialog(null, "Excluir este autor irá também excluir todos os livros e exemplares deste cadastrados.\nEscreva exatamente (SIM) para confirmar, qualquer outro texto irá cancelar.");
            if(input.equals("SIM")){
                AutoresDAO dao = new AutoresDAO(Conector.conectar());
                dao.excluir(id);
                listener.sinalglobal();
            }
            else{
                JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
            }
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    public void setListener(GlobalInterface listener){
        this.listener = listener;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAutor;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbMovimento;
    private javax.swing.JLabel LbNome;
    // End of variables declaration//GEN-END:variables
}
